### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by miguelsasso** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#106]
Cannot login, updated app, accepted new terms & conditions, hard coded version to 1.19.0 per apple App Store. 

Anyone else?

**Comment by mkz212** [comment]
Same for me. From today.

**Comment by arkadicolson** [comment]
Same here: Tried reverted version 1.7.3 with the same result...

[Homebridge Panasonic AC Platform] Login failed. Skipping device discovery.
[12/11/2023, 10:55:40 AM] [Homebridge Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment.The plugin will try to log in again in 12 minutes.
[12/11/2023, 10:55:40 AM] [Homebridge Panasonic AC Platform] If the issue persists, make sure: configured is the correct email and password in plugin settings,field "Emulated Comfort Cloud app version (override)" in settings is empty or have the latest version of Panasonic Comfort Cloud from the App Store (like 1.19.0), the latest version of this plugin is installed, all terms and conditions after logging into the Panasonic Comfort Cloud app are accepted. Restart Homebridge if you change plugin settings.

**Comment by mkz212** [comment]
THIS IS NOT A PROBLEM WITH THIS PLUGIN! 

- Other plugins (also for comfort cloud) do not work either!
- Panasonic had a technical break tonight - they probably changed something in the API (AGAIN!)

**Comment by mkz212** [comment]
Try override version in settings to 1.19.1

**Comment by miguelsasso** [comment]
This new error msg really concerns me 

![IMG_2846](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/59859023/2028d5c6-d9d6-40dd-aaf1-f05adf86e981)

**Comment by mkz212** [comment]
> This new error msg really concerns me
> 
> ![IMG_2846](https://private-user-images.githubusercontent.com/59859023/289557571-2028d5c6-d9d6-40dd-aaf1-f05adf86e981.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDMzMzAsIm5iZiI6MTcwMjMwMzAzMCwicGF0aCI6Ii81OTg1OTAyMy8yODk1NTc1NzEtMjAyOGQ1YzYtZDlkNi00MGRkLWFhZjEtZjA1YWRmODZlOTgxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxMzU3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTk4MGEzMTAyZDdiMDBhMjZiMDM3YWUzOWY4N2YxZDMzMDNjY2IwNTYyZGE2MTYwZDcyMDYwMTFiODJjMmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1mPqVmwqIzPwGHBy_xZpkWUyqgnkqaV1E4kRB2Zksk)

Yes. Me too. I have already written to Panasonic to turn it off or give you a choice. But I didn't get an answer.

**Comment by mkz212** [comment]
Almost for sure the error is located on Panasonic's end, so we have to wait until they resolve this issue.

In the meantime, we have corrected the plugin code to better indicate errors and manage login process.

**Comment by embee8** [comment]
It looks like they have started to crack down on unofficial applications. As such, I don't think there will be a "resolution" to this issue from the manufacturer. They have every right to prevent unauthorised apps from talking to their services, as unfortunate that may be for community projects like this one.

> THIS IS NOT A PROBLEM WITH THIS PLUGIN!

This is a problem with this and any other plugin that use similar APIs. We can hardly blame the manufacturer for making sure the T&Cs are followed.

> I have already written to Panasonic to turn it off or give you a choice. But I didn't get an answer.

What do you expect? I assume the purpose of this move is to make people use the official apps. Best case would be if they are working on official HomeKit support, which would save us a lot of time and trouble.

**Comment by mkz212** [comment]
In another house I have Gree and there plugin has not been updated for 2 years and everything works flawlessly. Ehh.. Panasonic still has to change something...

**Comment by jandersonhill** [comment]
I'm concerned Panasonic might be clamping down on useful home integration tools such as this (well, at least until they support HomeBridge!).

That said, @mkz212 has pointed out that, if you log out of and back into the Comfort Cloud app, it says 'Login ID or password is incorrect', which suggests there maybe an issue at their end.

**Comment by mkz212** [comment]
Now, when Panasonic unlock my account, again I can login in Panasonic Comfort Cloud app but in Homebridge I have error 500 😞

**Comment by jandersonhill** [comment]
I've just tested and am getting the same here. Do you think we could use WireShark to look at what's going on?

**Comment by mkz212** [comment]
@jandersonhill I still hope that it will be good because browsing the Internet I encountered many such threads from different periods of time and those problems were somehow solved, most often Panasonic changed something in API and that's it. You can try.

**Comment by mitchelp** [comment]
Noticed the same issues regarding this at the github repo for the HACS plugin (home assistant).
For example: https://github.com/sockless-coding/panasonic_cc/issues/147#issuecomment-1851310578

They claim, that after accepting 2 to 3 new EULA stuff it started working again. So I figured I logout off the comfort cloud app, and log back in. But I already accepted the new EULA stuff and unfortunately this didn't fix the error 500 for this homebridge plugin.

**Comment by mitchelp** [comment]
> Noticed the same issues regarding this at the github repo for the HACS plugin (home assistant). For example: [sockless-coding/panasonic_cc#147 (comment)](https://github.com/sockless-coding/panasonic_cc/issues/147#issuecomment-1851310578)
> 
> They claim, that after accepting 2 to 3 new EULA stuff it started working again. So I figured I logout off the comfort cloud app, and log back in. But I already accepted the new EULA stuff and unfortunately this didn't fix the error 500 for this homebridge plugin.

Oke I did some more investigastion, and it seems highly unlikely that anything is working at the moment. When I manually push the same auth request to the the auth URL that is used for this plugin as-well as the Home Assistant version, I get the following error:

```
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
```
So maybe, panasonic did change the auth / API location. Or they still have issues.
What is kinda strange, because I was able to re-login using the Comfort Cloud APP. 🤔 ....

**Comment by mkz212** [comment]
I don't see any EULA to accept. Still have error 500.

**Comment by mkz212** [comment]
@mitchelp 

If they changed something or have a problem, at the beginning they all had an error 500 in HB and in the Panasonic application they could connect.

But due to too many error logging attempts from HB, these accounts were blocked and then in HB error 429 and in the application information about blocking for 24h.

Now there is no 24 h ban and we return to error 500 again.

**Comment by mitchelp** [comment]
@mkz212 there must be a change somewhere at Panasonic. Because why is it possible to (re) sign in to the comfort cloud app, and impossible for the homebridge plugin to sign in.  So this needs some research.

**Comment by mkz212** [comment]
@mitchelp That's what I wrote - either they changed something or something doesn't quite work. A few months ago they also changed something and it didn't work - then a new header had to be added. Do you have the option to check what commands the working application sends?

**Comment by mitchelp** [comment]
@mkz212  I tried, but i'm not that well experienced with intercepting traffic. It also uses SSL what doesn't make it easier. 😄 Maybe someone else is more experienced with this?

**Comment by mitchelp** [comment]
I don't get it @mkz212 how can it work for people here:
https://github.com/sockless-coding/panasonic_cc/issues/147

I looked at the code, and this plugin uses the following payload towards auth/login:
```
        payload = {
            "clientId": self._settings.clientId,
            "language": "0",
            "loginId": self._username,
            "password": self._password
        }
```

And this plugin does the following:
```
    return axios.request<ComfortCloudAuthResponse>({
      method: 'post',
      url: 'https://accsmart.panasonic.com/auth/login',
      headers: this.getBaseRequestHeaders(),
      data: {
        'loginId': this.config.email,
        'language': '0',
        'password': this.config.password,
      },
    })
```

Maybe the `clientId` is missing? Or did I mis it in de code somwhere? Or it is added here?:
https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/blob/6af81143455360c064bf1d58b7bf249841a26776/src/types.ts#L28

**Comment by mkz212** [comment]
@mitchelp 

I also watched this thread and looked through this code. I also tried to combine with adding clientId and changing headers - but I failed to achieve anything. I also do not understand why one works there and another does not.

**Comment by mitchelp** [comment]
I noticed your replies in the thread @mkz212, the only noticeable difference was the clientId. Really strange indeed that one is working and another isn't. Seems to me impossible.

I also don't think this is related to a blockage for my IP, because the official app is working just fine.

**Comment by mkz212** [comment]
> I noticed your replies in the thread @mkz212, the only noticeable difference was the clientId. Really strange indeed that one is working and another isn't. Seems to me impossible.
> 
> I also don't think this is related to a blockage for my IP/User, because the official app is working just fine.

If you had a ban, the error code in HB would be 429, not 500.

**Comment by mkz212** [comment]
They blocked my account again for 24 hours due to incorrect login attempts. 😓

**Comment by mitchelp** [comment]
I've added 2 accounts to my AC to prevent this ^

**Comment by mkz212** [comment]
> I've added 2 accounts to my AC to prevent this ^

It doesn't make a difference to me because I don't use a bad application from Panasonic anyway 😅

**Comment by jandersonhill** [comment]
I had a look at the Cloudflare side of things and found the following:

‘Error 403 from Cloudflare is a forbidden status code. You get this response when trying to scrape a website as a bot. That can happen when using tools like Python, NodeJS, cURL, etc. The security service assumes you're a threat and displays an Error 1020 screen, representing the 403 status code.’

**Comment by jandersonhill** [comment]
Looking briefly at the app that appears to be working, they are using the python library: pypi.org/project/urllib3/ as the HTTP client, which may not be blocked.

It's possible that changing the HTTP library we are using to something else might work, but it's only a matter of time before that also fails. There is an alternative mentioned here that appears to impersonate a specific JA3 fingerprint, but I haven't had the time to read through it yet:

https://medium.com/cu-cyber/impersonating-ja3-fingerprints-b9f555880e42

**Comment by mkz212** [comment]
https://github.com/sockless-coding/panasonic_cc

In this plugin, it is said that some users work. Here I see that there is some SSL certificate.

**Comment by mlpplm** [comment]
> Looking briefly at the app that appears to be working, they are using the python library: pypi.org/project/urllib3/ as the HTTP client, the fingerprint of which may not be blocked by Cloudflare.

No luck:
----
import json
import urllib3
url = "https://accsmart.panasonic.com/auth/login"
headers = {
    "Accept": "application/json; charset=UTF-8",
    "Content-Type": "application/json",
    "User-Agent": "G-RAC",
    "X-APP-TYPE": "0",
    "X-APP-TIMESTAMP": "1",
    "X-APP-NAME": "Comfort Cloud",
    "X-CFC-API-KEY": "Comfort Cloud",
    "X-APP-VERSION": "1.19.0",
}

with open("pana.json", "r") as file:
    data = file.read()
http = urllib3.PoolManager()
response = http.request(
    "POST",
    url,
    headers=headers,
    body=json.dumps(json.loads(data)).encode("utf-8"),
)
print(response.status)
print(response.data.decode("utf-8"))
-------

pana.json: 
{
   "loginId":"xxxxx@xxxx.com",
   "language":"0",
   "password":"XXXXX"
}

->500
{"code":5001,"message":"DB system error due to db system"}

**Comment by jandersonhill** [comment]
> No luck:

You're getting the original error code, as opposed to the Cloudflare rejection error code - it's possible they are related, but I'd like to be sure. If I have a moment this evening, I'll try to run your code in my environment.

It's also possible we're hitting two layers of protection...

**Comment by mkz212** [comment]
https://github.com/sockless-coding/panasonic_cc/issues/147#issuecomment-1852777101

**Comment by jandersonhill** [comment]
Ok, looking at the work done in the link above, it does seem they're using certificates plus other measures to prevent third-party use of the API. What I find silly is that Panasonic's AC division are relegating themselves from a brand that could be recommended for use in smart homes to one that cannot.

**Comment by mitchelp** [comment]
Well it is going to take some time, but someone will reverse engineer this, and than we can use it again.

**Comment by jandersonhill** [comment]
Agreed

**Comment by mkz212** [comment]
I added PR that solves the problem!

**Comment by arkadicolson** [comment]
A quick release would be nice ;-)

**Comment by ridzria** [comment]
Same problem here too. Though new version `1.8.4` is released but it isn't showing in `homebridge`.

**Comment by mkz212** [comment]
It should be visible soon.

**Comment by jandersonhill** [comment]
Trying to release, but the workflow failed. Am looking into this now...

**Comment by mkz212** [comment]
Version 1.8.4 released! If this solves the problem, please close the Issue.

**Comment by mstendah** [comment]
> Version 1.8.4 released! If this solves the problem, please close the Issue.

Did not solve it for me. I still get this when trying to reinstall the integration

![image](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/19377422/c4767a12-538c-4622-9acb-c0c804bb3b2b)
--
This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:60
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 11:26:19 (1 occurrences)
Last logged: 11:26:19

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}

**Comment by mkz212** [comment]
I thought it was a Homebridge plug? And you will show me Home Assistant.

**Comment by mstendah** [comment]
> > Version 1.8.4 released! If this solves the problem, please close the Issue.
> 
> Did not solve it for me. I still get this when trying to reinstall the integration
> 
> ![image](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/19377422/c4767a12-538c-4622-9acb-c0c804bb3b2b)
> --
> This error originated from a custom integration.
> 
> Logger: custom_components.panasonic_cc.config_flow
> Source: custom_components/panasonic_cc/config_flow.py:60
> Integration: Panasonic Comfort Cloud (documentation, issues)
> First occurred: 11:26:19 (1 occurrences)
> Last logged: 11:26:19
> 
> Unexpected error creating device
> Traceback (most recent call last):
>   File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
>     devices = await self.hass.async_add_executor_job(api.get_devices)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
>     self.login()
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
>     self._create_token()
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
>     raise ResponseError(response.status_code, response.text)
> custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}
> 

My bad. I just did not get the update at first (looked for it in the wrong place first, found it then in HACS). Now up an running again.

Many many thanx!

**Comment by miguelsasso** [comment]
Hello

Can confirm the update has fixed the issue. 

Really really appreciate your efforts to keep this working. 

Thanks, Miguel

**Comment by miguelsasso** [comment]
Closing

**Comment by miguelsasso** [comment]
Oops. Closing.
