### ISSUE TITLE
Plugin icon

### ISSUE THREAD

**Issue by mkz212** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#114]
@embee8 @jandersonhill 

Now you can add plugin icon. Admin of the plugin must fill this form: 

https://github.com/homebridge/verified/issues/new?assignees=&labels=&projects=&template=icon-request.yml&title=Plugin+Icon+Request

My icon suggestion for this plugin:

![homebridge-panasonic-ac-platform](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/1e62968d-f2b8-4879-8847-d960c6a0b9eb)

**Comment by jandersonhill** [comment]
While the icon looks appropriate, I think we'll find we would likely need permission from Panasonic to use it, otherwise it will likely end up in a legal dispute. I'll look to see if they have any published guidelines on usage.

**Comment by mkz212** [comment]
You can see other logos here: https://github.com/homebridge/verified/tree/latest/icons

**Comment by jandersonhill** [comment]
If you mean that we can get away with it because others do, I would highly recommend against this (especially under the current circumstances).  I have some experience of how this works and it can be like poking a bear with a sharp stick. I've seen projects close as a result of the expensive legal action that followed.

**Comment by mkz212** [comment]
No, just shows examples, e.g. if there were to be a different logo

**Comment by mkz212** [comment]
@jandersonhill I changed the logo.

**Comment by jandersonhill** [comment]
Yeah, that's cool! (assuming it's copyright-free)

**Comment by jandersonhill** [comment]
Requested!

**Comment by mkz212** [comment]
@jandersonhill I corrected this logo. And now I also gave PSD because I forgot to save as PSD to previous version. Can you Replace in the request because I see that they have not accepted yet?
