### ISSUE TITLE
Support for multiple homes

### ISSUE THREAD

**Issue by Zaphod8** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#155]
I have 2 Panasonic aircon units in my house. I also have 1 in another house (parents). 

Comfort Cloud supports these being allocated to different homes. 

The plug-in puts them all, including the one not in my house, into my home in the Home app.

is multi-home support possible?

**Comment by mkz212** [comment]
Multi home is not possible. The only thing that comes to my mind is to add the possibility of exclude one or more AC from adding to HomeKit. So in 1 house there would be all minus 1 and in the second all minus two. Only in this way on one account can you make in two different houses there are different ACs. But for this, you need to have a separate homebridge in each house and a separate account for Apple Homekit.

**Comment by mkz212** [comment]
@Zaphod8 Option to exclude devices added in 1.9.0 beta. Can you install and test?

**Comment by Zaphod8** [comment]
Seems to work ok. The log message is a little obscure though.

"[1/14/2024, 7:02:06 PM] [Homebridge Panasonic AC Platform] Removing accessory 'Mum - Aircon' (Cxxxxxxxxx) because it does not exist on the Comfort Cloud account (anymore?).”

Maybe something like:

"[1/14/2024, 7:02:06 PM] [Homebridge Panasonic AC Platform] Removing accessory 'Mum - Aircon' (Cxxxxxxxxx) because it has been manually excluded.”


Comfort Cloud allows for multiple homes and lists each aircon under the appropriate home. So there must be some meta data associated with each accessory identifying which home it belongs to?

Would it be more logical to provide an option to enter a home name and only load accessories associated with that home? If no home is specified just load them all?

Thanks for all the work supporting this.

**Comment by mkz212** [comment]
@Zaphod8 

I corrected the log - it will be in the next beta. There is one function for removing old devices, when excluded, and when you remove it from CC account, so log for this operation is also one.

As for the option with giving the name of the house, thanks for the suggestion but:
- first of all, I think that the exclude devices option is enough, usually all ACs from a given account are added anyway. 
- the exclude devices option is more accurate than choosing a house
- in reponse API(as I quick checked it) I do not see that there is an assignment to a given house

**Comment by Zaphod8** [comment]
This is the main screen from Comfort Cloud. Somehow it knows which house the accessories are in. That must be in the data it receives somewhere. CamOn 14 Jan 2024, at 19:58, mkz212 ***@***.***> wrote:﻿
@Zaphod8
I corrected the log - it will be in the next beta. There is one function for removing old devices, when excluded, and when you remove it from CC account, so log for this operation is also one.
As for the option with giving the name of the house, thanks for the suggestion but:

first of all, I think that the exclude devices option is enough, usually all ACs from a given account are added anyway.
the exclude devices option is more accurate than choosing a house
in reponse API(as I quick checked it) I do not see that there is an assignment to a given house

**Comment by mkz212** [comment]
@Zaphod8 You can make a Pull Request with a solution to it. As for me, it is not needed.

**Comment by Zaphod8** [comment]
Agree. I suspect there are few people who operate across multiple houses. On 14 Jan 2024, at 22:46, mkz212 ***@***.***> wrote:﻿
@Zaphod8 You can make a Pull Request with a solution to it. As for me, it is not needed.
