### ISSUE TITLE
Please stop spamming logs for every API refresh

### ISSUE THREAD

**Issue by xyz667** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#201]
Currently for every refresh at the API the current temperatures and operation modes of all devices are output to the log. This results in my Homebride log consisting of not much more than this plugin‘s output for (IMO) pure debug info. Please, could you stop that or tie it to the set loglevel.

**Comment by mkz212** [comment]
@xyz667 Done in #202

**Comment by mkz212** [comment]
@xyz667 version 2.1.0-beta.1 just released. It contains the solution you wanted - the ability to choose what level of logs to display.

**Comment by xyz667** [comment]
> @xyz667 version 2.1.0-beta.1 just released. It contains the solution you wanted - the ability to choose what level of logs to display.

Thank you very much! Seems to work as expected.
