### ISSUE TITLE
An error has occured during device discovery...

### ISSUE THREAD

**Issue by clw123456** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#234]
Hi All,
Hope you're good. Nothing changed in my setup, but control of my 2 AC units has stopped working. Any one able to help me troubleshoot please? Just made sure everything was up to date, and tried reboots etc but no joy.

Thanks for any help!

Log:

20/03/2024, 15:42:59Panasonic AC BridgeLoaded plugin 'homebridge-panasonic-ac-platform'
20/03/2024, 15:42:59Panasonic AC BridgeLoading 1 platforms...
20/03/2024, 15:42:59Panasonic AC BridgeHomebridge Panasonic AC PlatformLoading accessory 'Upstairs' from cache.
20/03/2024, 15:42:59Panasonic AC BridgeHomebridge Panasonic AC PlatformLoading accessory 'Garage' from cache.
20/03/2024, 15:43:00Panasonic AC BridgeBridge is running on port 51856.
20/03/2024, 15:43:01Panasonic AC BridgeHomebridge Panasonic AC PlatformThe latest App Store version is 1.20.1.
20/03/2024, 15:43:01Panasonic AC BridgeHomebridge Panasonic AC PlatformUTC date: 2024-03-20 15:43:01
20/03/2024, 15:43:01Panasonic AC BridgeHomebridge Panasonic AC PlatformLocal date: 2024-03-20 15:43:01
20/03/2024, 15:43:01Panasonic AC BridgeHomebridge Panasonic AC PlatformNo 2FA key or incorrect key
20/03/2024, 15:43:02Panasonic AC BridgeHomebridge Panasonic AC PlatformERRORComfort Cloud - login(): Error
20/03/2024, 15:43:02Panasonic AC BridgeHomebridge Panasonic AC PlatformSuccessfully logged in to Comfort Cloud.
20/03/2024, 15:43:02Panasonic AC BridgeHomebridge Panasonic AC PlatformERRORAn error occurred during device discovery. Turn on debug mode for more information.

**Comment by clw123456** [comment]
I was able to login via the iPhone app all ok

**Comment by mkz212** [comment]
Restart wifi in AC (or disconnect AC from power and connect again). Restart Homebridge. Restart routers.

**Comment by mkz212** [comment]
I checked at home now. I restarted Homebridge and the plugin logged in and controls AC without any problem. 

Did you set 2FA in your Panasonic Comfort Cloud (in app) ? TOTP os SMS?

**Comment by mkz212** [comment]
You can enable debug to see more info in log.

**Comment by clw123456** [comment]
Ok interesting. I did already have SMS 2FA setup, I've now reset that and configured it again. Rebooted everything, enabled debug but still getting same error in the logs...

20/03/2024, 16:30:07Panasonic AC BridgeLoaded plugin 'homebridge-panasonic-ac-platform'
20/03/2024, 16:30:07Panasonic AC BridgeRegistering platform 'homebridge-panasonic-ac-platform.Panasonic AC Platform'
20/03/2024, 16:30:07Panasonic AC BridgeLoading 1 platforms...
20/03/2024, 16:30:07Panasonic AC BridgeHomebridge Panasonic AC PlatformLoading accessory 'Upstairs' from cache.
20/03/2024, 16:30:07Panasonic AC BridgeHomebridge Panasonic AC PlatformLoading accessory 'Garage' from cache.
20/03/2024, 16:30:07Panasonic AC BridgeBridge is running on port 51856.
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformThe latest App Store version is 1.20.1.
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformUTC date: 2024-03-20 16:30:08
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformLocal date: 2024-03-20 16:30:08
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformNo 2FA key or incorrect key
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformERRORComfort Cloud - login(): Error
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformSuccessfully logged in to Comfort Cloud.
20/03/2024, 16:30:08Panasonic AC BridgeHomebridge Panasonic AC PlatformERRORAn error occurred during device discovery. Turn on debug mode for more information.

**Comment by mkz212** [comment]
> Debug is enabled in the plugin and also in the log view, but doesnt appear to display many extra lines.

You need yo enable debug mode in Homebridge settings. And restart Homebridge.

**Comment by mkz212** [comment]
In plugin settings, field Emulated Comfort Cloud app version, is empty? (Should be)

**Comment by mkz212** [comment]
The only thing that comes to my mind is to set the TOTP method instead of SMS. I have TOTP and it works.

@jandersonhill any idea?

**Comment by clw123456** [comment]
Clearing that field for Emulated version fixed it btw! Thanks for that tip.

(I had an AppVersionOverride line in the config from when this was an issue a long time ago also).

So strange as I've been using this for ages and hadn't made any changes.

**Comment by mkz212** [comment]
Panasonic raised its API version yesterday. If this field is empty, plugin automatically get API versions. Please close Issue.

**Comment by clw123456** [comment]
All good, thanks for the quick help.
