### ISSUE TITLE
FAN only mode is not found (Only Cool/Heat/Auto shown in HomeKit)

### ISSUE THREAD

**Issue by cyrusauyeungc** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#242]
hello, my air con unit does support
Auto/Cool/Heat/dehumid/Fan only
however, in the HomeKit accessories, only Cool/Heat/Auto is found.
in the cloud comfort app it's available and working as expected.

Is there any way the FAN only mode can be added?
thanks.

**Comment by mkz212** [comment]
Done in #243 . Will be in next beta or public release.

**Comment by cyrusauyeungc** [comment]
Thanks and appreciate that. happy to mark it as closed.

**Comment by mkz212** [comment]
@cyrusauyeungc 2.2.0-beta.1 just released. Can you try?

**Comment by cyrusauyeungc** [comment]
thanks @mkz212 for the notification. will update the plugin now and keep you posted!

**Comment by cyrusauyeungc** [comment]
yes it's confirmed working. 
When Auto is selected in HOME, FAN mode would be on directly.

<img width="756" alt="image" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/69232468/064305bc-5892-4c37-80cf-7dd6b188f445">
