### ISSUE TITLE
Status no longer Bi-Directional?

### ISSUE THREAD

**Issue by clw123456** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#265]
Hi All,
I've noticed the status of my AC units in Homekit no longer updates bi-directionally. I swear this used to happen! :) (but correct me if not).

i.e. if I turn on an AC unit with its hardware remote or use Comfort Cloud app, this will not update in the homekit view automatically.

Any ideas?

**Comment by mkz212** [comment]
@clw123456 In plugin settings you have field to set refresh time. Minimum is 10 min.

**Comment by clw123456** [comment]
Cool thanks @mkz212 ! Just added this in - are the integer values seconds or minutes?

Any idea what changed also, I seem to remember the two way sync being relatively slick without me adding any additional config?

**Comment by mkz212** [comment]
@clw123456 

Values are in minutes. But you cannot set any value - minimum 10, otherwise refresh will be disabled. 

This change was introduced to reduce the number of queries to the Comfort Cloud server. By too many (i.e. too frequent refresh) they blocked accounts or entire APIs.

**Comment by mkz212** [comment]
@clw123456 Take a look: #272 - new version 3.0.0 with many new options. We invite to tests.
