### ISSUE TITLE
Temperature Reading from Outdoor Unit

### ISSUE THREAD

**Issue by 1homebridge** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#268]
Hi. I have 8 units linked to my Comfort Cloud Account but only one is showing the Temperature Reading from the Outdoor Unit. It seems to be the unit I turned on first since the last update. Is there a way to resolve this?

![IMG_1299](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/90335348/47e18b84-f9ec-495d-8816-e47cf707c10c)

**Comment by mkz212** [comment]
@1homebridge 

Nothing has changed in the code regarding temperatures from outdoor units. 

It works like this: 
- if the indoor unit has a temperature sensor, it is displayed, 
- else if the outdoor unit has a sensor, it is displayed
- if there are no internal and outdoor sensor, a constant temperature value is used depending on the selected mode.

**Comment by mkz212** [comment]
@1homebridge Maybe this will help: #272

**Comment by mkz212** [comment]
@1homebridge 

Ok, I think I already know what you meant. I think I misunderstood before. Version 3.0.0 should solve this problem. You can already install the beta version and test or wait for the public version, but I don't think it will be different anymore from latest beta.

**Comment by mkz212** [comment]
New version solves this problem. Unfortunately, Panasonic has changed the API and no version is currently working. We are working on it: #330
