### ISSUE TITLE
Version 3.0.0 - test beta!

### ISSUE THREAD

**Issue by mkz212** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#272]
# Version 3.0.0

WARNING! Read carefully before updating!

- This version introduces a huge novelty, from now on you can choose settings for each device separately. Fields such as: Oscilate Switch, Auto Mode, Force Nanoe, Force Swing, Force Inside Cleaning, Force Eco Navi, Minimum Heating Temp. and Expose Outdoor Unit, from now on are individual for each device.
- Possibility to add for each indoor unit a virtual temperature sensor that will show the temperature from the outdoor unit (connected to the selected indoor unit). Now every virtual sensor will have same name as indoor unit with note "(outdoor)". 
- Fixed the login and error mechanism.
- Redesigned layout of plugin config.
- Improvements to log.
- Minor bugs and dependency updates.

WARNING!
The update may involve the fact that some fields in the plugin settings will have to be filled in again and /or some devices or virtual temperature sensors for outdoor units could need to be reconfigured in HomeKit. 

# Most important things to test in beta:
Add all your devices in plugin config (by name or serial number) and restart Homebridge or plugin bridge. In logs after restart you will see how many devices are in Comfort Cloud account, how many devices are added in plugin config. If there is some devices wrong added to plugin config you will see a message in log. 

1.  In plugin config, in one device, try select field "Exclude device". Restart. Did this device disappear from HomeKit? 
2. In plugin config, in at least two devices, try select field "Expose Outdoor Unit". Restart. Did it correctly add two temperature sensors from external units? (Same name as device but with note "Outdoor Unit"). The temperature is only collected when the device is turned on.
3. Try other things, like force Nanoe, Swing directions etc.

### How to install 3.0.0 beta?
Go to Homebridge > Plugins and from plugin dropdown menu select "Install other version", select 3.0.0 beta and install.

**Comment by xyz667** [comment]
Could you explain the design change with regard to the outdoor unit?
I have multiple indoor units und one outdoor unit, which is (obviously) located outside the house. Why would I want to attach that outdoor unit to a specific indoors unit, let alone multiple indoor units? It is a separate device which is **never** in the same HomeKit „room“ as any indoors device.

**Comment by mkz212** [comment]
> Could you explain the design change with regard to the outdoor unit? I have multiple indoor units und one outdoor unit, which is (obviously) located outside the house. Why would I want to attach that outdoor unit to a specific indoors unit, let alone multiple indoor units? It is a separate device which is **never** in the same HomeKit „room“ as any indoors device.

This plugin adds only indoor units. But you can for each indoor unit add dummy (virtual only) temperature sensor and it will display temperature from outdoor unit that is connected to this indoor unit.

**Comment by xyz667** [comment]
> > Could you explain the design change with regard to the outdoor unit? I have multiple indoor units und one outdoor unit, which is (obviously) located outside the house. Why would I want to attach that outdoor unit to a specific indoors unit, let alone multiple indoor units? It is a separate device which is **never** in the same HomeKit „room“ as any indoors device.
> 
> This plugin adds only indoor units. But you can for each indoor unit add dummy (virtual only) temperature sensor and it will display temperature from outdoor unit that is connected to this indoor unit.

But there is only one outdoor unit, connected to all indoor units at the same time? Why would I duplicate this single device?
Also I have noticed that indoor devices print an outdoor temperature in the log, even if no outdoor device is attached. Why?

**Comment by mkz212** [comment]
@xyz667 

The logs show you the information received from Comfort Cloud. In the settings, you can choose what information should be displayed.

The "expose outdoor unit" option is used to create a virtual temperature sensor in Apple Home. You can create as many virtual sensors as many indoors devices you have - of course, if you have an installation such that there is many indoot units but only one external unit, then each of these sensors will show the same temperature.

**Comment by xyz667** [comment]
> The logs show you the information received from Comfort Cloud. In the settings, you can choose what information should be displayed.

I just noticed that Comfort Cloud data is really wonky. Comfort Cloud has different outdoor temperatures for the indoor units (also in the Panasonic app) - although they are all connected to the very same outdoor unit?!
Your design is understandable that way, you replicate the CC data (however unreliable that is, but that‘s Panasonic‘s fault).

**Comment by mkz212** [comment]
@xyz667 

Unfortunately, I have no influence on the data from Comfort Cloud. You have to write to Panasonic

As for the plugin, I am not its creator - I develop it only and update for what users need.

**Comment by mkz212** [comment]
@xyz667 

It seems to me that the temperature from the outdoor unit is updated only when the indoor unit is turned on. Hence the difference may be that it was updated at different times.

In addition, remember that the plugin updates data from the frequency selected in the settings (it could also be disabled).
