### ISSUE TITLE
Feature request - Override indoor temp reading

### ISSUE THREAD

**Issue by hubert3** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#284]
I have an older Panasonic unit bought in 2016 (wifi module added later) where the official Comfort Cloud app shows no indoor temperature reading, so the plugin reports the outdoor temp as the room temperature.

I have a Z-Wave device in that room which has a temperature sensor, so I have a cron job independent of Homebridge that fetches the room temperature from that device into a text file every few minutes, and I patched my copy of this plugin to read the temp from that file, as shown below.

My solution is a bit hacky but it works. Probably not many people will use this, but would it be possible to have a configurable option to override the indoor temp reading and read it from a local file instead? (This would save me having to update my patch every few versions)

```
--- /usr/lib/node_modules/homebridge-panasonic-ac-platform/src/accessories/indoor-unit.ts	2024-02-28 00:17:47.154645438 +1100
+++ ./indoor-unit.ts	2024-02-28 00:28:47.080758951 +1100
@@ -2,6 +2,7 @@
 import PanasonicPlatform from '../platform';
 import OutdoorUnitAccessory from './outdoor-unit';
 import { ComfortCloudDeviceUpdatePayload, PanasonicAccessoryContext } from '../types';
+import * as fs from 'fs';
 import {
   ComfortCloudAirSwingLR,
   ComfortCloudAirSwingUD,
@@ -144,25 +145,11 @@
       // be used: 8°C for heating and 30°C for cooling.
       // Temperature of 126 from the API = null/failure

-      if (deviceStatus.insideTemperature < 126) {
-        this.service.updateCharacteristic(
-          this.platform.Characteristic.CurrentTemperature, deviceStatus.insideTemperature);
-        logOutput += `Indoor Temp. ${deviceStatus.insideTemperature}, `;
-      } else {
-        this.platform.log.debug('Indoor temperature: is not available');
-        if (deviceStatus.outTemperature < 126) {
-          this.service.updateCharacteristic(
-            this.platform.Characteristic.CurrentTemperature, deviceStatus.outTemperature);
-          logOutput += `Indoor Temp. (from Outdoor) ${deviceStatus.outTemperature}, `;
-        } else {
-          this.platform.log.debug(
-            'Indoor and Outdoor temperature are not available - setting default temperature');
-          this.service.updateCharacteristic(
-            this.platform.Characteristic.CurrentTemperature,
-            (deviceStatus.operationMode === 3) ? 30 : 8,
-          );
-        }
-      }
+      this.platform.log.debug('Returning indoor temp from /tmp/bedroom_temp');
+      this.service.updateCharacteristic(
+        this.platform.Characteristic.CurrentTemperature,
+        parseInt(fs.readFileSync('/tmp/bedroom_temp', 'utf-8'))
+      );
```

**Comment by mkz212** [comment]
Thank you for this manual.

Unfortunately, Panasonic has changed the API and no version is currently working. We are working on it: #330

**Comment by jasone00** [comment]
@mkz212 We have just had a new multi-split system installed (outdoor unit CU-4Z80VBR, indoor units CS-Z35UD3RAW), and have found the units do not have a temperature sensor like others in this #284 and #31

Recognising the point that an external indoor sensor is best practice to measure temperature, is it possible to render the temperature from a separate/third party temperature sensor on the AC unit's Homekit icon instead of the default 8 deg C for heating / 30 deg C for cooling?

Thinking it would be ideal to use the temperature readings from a HomePod or a Hue Motion Sensor for example

![image](https://github.com/user-attachments/assets/f6bf2184-aebb-487a-b1a6-c14fb6ff5d98)

**Comment by mkz212** [comment]
> @mkz212 We have just had a new multi-split system installed (outdoor unit CU-4Z80VBR, indoor units CS-Z35UD3RAW), and have found the units do not have a temperature sensor like others in this #284 and #31
> 
> Recognising the point that an external indoor sensor is best practice to measure temperature, is it possible to render the temperature from a separate/third party temperature sensor on the AC unit's Homekit icon instead of the default 8 deg C for heating / 30 deg C for cooling?
> 
> Thinking it would be ideal to use the temperature readings from a HomePod or a Hue Motion Sensor for example
> 
> ![image](https://private-user-images.githubusercontent.com/178394235/373263847-f6bf2184-aebb-487a-b1a6-c14fb6ff5d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjE1NDQsIm5iZiI6MTcyNzk2MTI0NCwicGF0aCI6Ii8xNzgzOTQyMzUvMzczMjYzODQ3LWY2YmYyMTg0LWFlYmItNDg3YS1iMWE2LWMxNGZiNmZmNWQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMzE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2M1YmI3ZmMxMWFkZjUwNTRhYmMyOGJlYjA3ODIxOTk1MDg1ODc3MTU4MTI3ZWE1NjE2MmI0NjIwZTM0YWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kCzrOSHYUYkW5hODl5tJcvtYHa2EcGyji8dKlWs3PI4)

The plugin cannot read other devices (from different plugin) it does not have access to them. This possibility have only Homebridge and HomeKit. Therefore, the only solution is as it is now. In readme you will find an interpretation of how the temperature sensor works in the air conditioning.
