### ISSUE TITLE
Feature Request - Additional Switch for Eco Mode (not the same as Eco Navi)

### ISSUE THREAD

**Issue by anthonyhoi** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#377]
Hello,

For certain model, there is an “Eco Mode”.  Example here: [link](https://www.panasonic.com/global/hvac/products/comfort-cloud/how-to-use-comfort-cloud/activate-air-conditioner-eco-mode.html#:~:text=Note%20%3A%20A%20green%20leaf%20icon,control%20is%20enabled.&text=Air%20conditioner%20needs%20to%20be,are%20for%20illustration%20purposes%20only.)

It can be activated by sending - parameters.ecoFunctionData: _**2**_

![IMG_0048](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/16330891/5d022753-78aa-4b86-aee7-9335bfcbc27c)

By default, parameters.ecoFunctionData is set to the value “1”.

![IMG_0046](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/16330891/d7d20eb7-f55a-4612-81d1-c97e922d3cbf)

This was previously resolved in issue #73. But after the introduction of the switches, the value was not passed anymore. 

Can there be a new switch to control “Eco Mode” like how you control the other modes please?

Thanks!

**Comment by mkz212** [comment]
Panasonic could really do something with this names! 😋 Sure! I'll add in a moment! 👍 

This is separate function? I mean, does activation of this will disable any other function or is it totally independent? E.G activation of Heat mode will deactivate Cool mode or activation of Quiet mode will deactivate Powerful mode.

**Comment by mkz212** [comment]
v4.0.5 release - adds Eco Function.

**Comment by anthonyhoi** [comment]
Updated to the new version and Eco Function switch works!

Thanks for this buddy 😊.
