### ISSUE TITLE
Swing direction settings are not used

### ISSUE THREAD

**Issue by ursusHU** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#391]
In the latest version 4.0.5. turning of oscillation in  Homekit results always the same independently the settings made in the plugin itself.
It is always goes back to centered mode independently from the setting when oscillation turned off. Left right swinging doesn't work from Homekit when turning on oscillation.

**Comment by mkz212** [comment]
Thanks for the information. I'll fix it today or tomorrow.

**Comment by mkz212** [comment]
Ok, can you test 4.1.0-beta.6 ?

- Activation of Oscilate switch from HomeKit will set swing to auto (for up-down and left-right).
- Deactivation of the Oscilate switch from HomeKit will set desired positions - you can set them in plugin config.
- When refreshing data, it will activate switch if at least one of the swing modes be enabled (up-down or left-right or both), otherwise it will be turned off.
- For more control you can add additional switches for up-down swing and left-right swing.

**Comment by mkz212** [comment]
Version 4.1.0 published. Includes fixed Oscilate switch. For more control, you can add two switches to control independently Vertical and Horizontal swing. Thanks for your report. I also encourage you to report errors and/or suggestions in the future.

**Comment by ursusHU** [comment]
Hi, sorry didn't have time to check this out. Unfortunately the settings still not taken from the plugin. 
This works -> Activation of Oscilate switch from HomeKit will set swing to auto (for up-down and left-right).
This doesn't work -> Deactivation of the Oscilate switch from HomeKit will set desired positions - you can set them in plugin config.

**Comment by mkz212** [comment]
@ursusHU version 4.1.1 relesed, should fix all these.

**Comment by ursusHU** [comment]
@mkz212 zes, it works now. However the slider for the fan and the oscillation on/off button is now missing from Homekit. It is intended like that?

**Comment by mkz212** [comment]
@ursusHU version 4.1.2 released. It contains many corrections to swing mode. However, in some cases, it may be necessary to set again Swing Mode default positions for horizontal and vertical (in plugin config). By default both values are set to center.

**Comment by mkz212** [comment]
@Sillanmaki Plugin version 4.4.3?

**Comment by Sillanmaki** [comment]
> @Sillanmaki Plugin version 4.4.3?

Yes 4.4.3. All up to date. I think I have had this same bug in multiple versions after v4. My AC is CS-TZ35 if that matters.

**Comment by mkz212** [comment]
@Sillanmaki Try change value for up down position in plugin config for something else than 'up', save, then change for 'up'.

**Comment by Sillanmaki** [comment]
> @Sillanmaki Try change value for up down position in plugin config for something else than 'up', save, then change for 'up'.

I've tried that multiple times and also reinstalled the plugin and cleared device cache.

**Comment by mkz212** [comment]
Show me here your plugin config (JSON). Remove login and password.

**Comment by mkz212** [comment]
@Sillanmaki v4.4.4 should fix this.

**Comment by Sillanmaki** [comment]
> @Sillanmaki v4.4.4 should fix this.

Confirmed. Works great. Thank you a lot for quick responses and a fix 👍👍
