### ISSUE TITLE
New indoor temperature returns 0

### ISSUE THREAD

**Issue by steffenmoll** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#422]
The new sensor only returns 0 *C despite it actually being 24 *C

**Comment by mkz212** [comment]
Enable all logs in plugin settings and debug mode in homebridge settings and restart homebridge. Then it will shows you log. Paste here response, it will be something that contains `parameters {}`

**Comment by mkz212** [comment]
4.2.5 should fix this. You need to enable again sensor for inside temp.

**Comment by steffenmoll** [comment]
You're awesome!
