### ISSUE TITLE
Ability to change/define the 'config-name' for a given sensor/button

### ISSUE THREAD

**Issue by steffenmoll** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#423]
(Not sure if this actually is technically doable)

Having to rename the instances every time Homebridge is rebooting, so if possible to define the config names in the plugin config - which is being displayed to the end user - it would be very handy.

**Comment by mkz212** [comment]
What do you mean? Name what? Do you mean additional switches, etc.?

**Comment by mkz212** [comment]
Unfortunately, sometimes it happens that the name does not show. The simplest solution is to remove the device from the cache (Homebridge settings).

**Comment by mkz212** [comment]
Unfortunately, sometimes happens that the name does not show (it show only name of main device). The simplest solution is to remove the device from the cache (Homebridge settings). At the moment we have no other solution, it depends on Homebridge and HomeKit.

**Comment by steffenmoll** [comment]
Understandable. Thanks!
