### ISSUE TITLE
Fan Speed

### ISSUE THREAD

**Issue by cMikEtm** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#427]
It is not possible to switch from quite mode to automatic.

**Comment by mkz212** [comment]
You have version 4.2.6? 

In additional fan speed slider (vertical) when you set 100 (max-top) or in built-in slider (horizontal) when you set 8 (max-right) it will set auto mode and it disable quiet mode.

**Comment by cMikEtm** [comment]
In Version 4.2.6 I have to switch the original slider in homekit from 1 - quite mode to 2,3,4 or 5 before I can switch it to 8 - automatic. When I switch it from 1 to 8 it always goes back to 1 - quite mode. I tried it with to optional switches for quite mode and fan speed and it worked, but not with the original slider in HomeKit.
Now I went back to 4.1.5 and I can change everything with the original HomeKit slider.

**Comment by mkz212** [comment]
v. 4.2.7 released, it should fix this.

**Comment by cMikEtm** [comment]
Yes, updated, tested and it’s working. Thanks 🙏🏼

**Comment by cMikEtm** [comment]
Fixed
