### ISSUE TITLE
Auto Mode, and Cooler only device

### ISSUE THREAD

**Issue by panda-ng** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#444]
Nice and great plugin!

1. Is it possible to have Auto Mode (not Auto Fan) exposed? Mine window-type AC has Nanoe-X standalone mode (guess it is “equivalent” to fan mode). But it does have an Auto Mode (not so sure what it is but I guess it is auto between Cool and Dry).

2. Is it possible to configure cooler only? The HomeKit UI (circular/rotational dial) is not user friendly in my case of cooler only. 

3. In HomeKit UI, only can see Off/Heat/Cool/Auto, can it be customized to reflect Off/Cool/Dry/Nanoe-X to be closely resembling the unit?

Thanks a lot!

**Comment by mkz212** [comment]
@panda-ng 

1. Auto mode is between Cool and Heat. 

2. You can add switch to enable Cool Mode. Go to plugin config. 

3. No, we cannot customize it. You can add additional switches etc.

**Comment by mkz212** [comment]
In version 4.4.0 I added a switch to Auto mode.
