### ISSUE TITLE
Outdoor temp sensor

### ISSUE THREAD

**Issue by arkcolson** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#492]
### Description

Hi

I accidently removed the outdoor temp sensor in the home app. I'm now trying to bring it back but it doesn't work. Even not after removing the childbridge from the home app and clear cached accesories. Do I miss something?

Thx

### Plugin version

5.0.0

**Comment by mkz212** [comment]
I don't quite understand? It seemed to me that the switches and sensors assigned to the main device could not be removed. In any case, remove the main device (your AC) from the cache (Homebridge settings) and add what you need in the plugin settings, then restart child bridge.
