### ISSUE TITLE
Add data refresh interval in config

### ISSUE THREAD

**Issue by yaucp** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#499]
### Description

Allow the user to customize how often to refresh data when it is turned off or turned on in configs

### Plugin version

v5.0.0

**Comment by mkz212** [comment]
We do not plan this because more frequent refreshes cause too many requests to the Panasonic server and therefore IP blocks and API changes.

**Comment by yaucp** [comment]
oh ok then that's unfortunate. thanks for your answer
