### ISSUE TITLE
Better way to handle login failure

### ISSUE THREAD

**Issue by mkz212** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#59]
Hi.

I think I have better solution for failed logins. Instead of making only 5 atempts to login, increase delay on every try, so first try will be after 5 minutes, second after 10, third after 30 and every next after hour. In this situation You don't need restart homebridge. I also add info to accept Panasonic terms to log.

   ```
  .catch(() => {
         this.log.error('Login failed. Skipping device discovery.');
         this.noOfFailedLoginAttempts++;
         
		 if this.noOfFailedLoginAttempts == 1 {
			 this.loginDelay = 300 * 1000;
		 }
	 	 else if this.noOfFailedLoginAttempts == 2 {
		 	this.loginDelay = 600 * 1000;	
		 }
 	 	 else if this.noOfFailedLoginAttempts == 3 {
 		 	this.loginDelay = 1800 * 1000;	
 		 }
 	 	 else {
 		 	this.loginDelay = 3600 * 1000;	
 		 }
 	 
		
         this.log.error('The Comfort Cloud server might be experiencing issues at the moment. ' +
                 `The plugin will try to log in again in ${this.loginDelay / 60000} minutes. ` +
                 'If the issue persists, make sure you configured the correct email and password ' +
                 'and run the latest version of the plugin. ' +
		 'If you run into login errors despite using the correct login details,' +
	         'make sure you accepted the latest terms and conditions after logging into the Comfort Cloud app.' +
                 'Restart Homebridge when you change your config.');
             
		this._loginRetryTimeout = setTimeout(this.loginAndDiscoverDevices.bind(this), this.loginDelay);

}
```

**Comment by mkz212** [comment]
And after succesfull login reset this.noOfFailedLoginAttempts to 0.

**Comment by embee8** [comment]
> And after succesfull login reset this.noOfFailedLoginAttempts to 0.

The current implementation does this, see [here](https://github.com/embee8/homebridge-panasonic-ac-platform/blob/811fc16af2b7e5e3130e2e7eab7cb4ae827cb03a/src/platform.ts#L131).

> Instead of making only 5 atempts to login, increase delay on every try, so first try will be after 5 minutes, second after 10, third after 30 and every next after hour.

Your code suggestion above does the same thing as the current implementation, only in larger intervals and it never stops retrying. If the login details aren't correct or the user didn't accept the T&Cs, we will keep retrying and increasing the log size for no additional benefit.

> In this situation You don't need restart homebridge.

Can you elaborate on "this situation"? In other words, can you explain when and how your suggestion performs differently than what we have now (besides what we have established above)?

**Comment by mkz212** [comment]
Your solution will stop working after 30 minutes, mine doesn't. If Panasonic makes a maintenance outage of more than 30 minutes, your solution will make the plugin stop working until homebridge is restarted. 

What if we're on vacation for 2 weeks and we can't restart homebridge? 

It's better to remove this switch altogether, because the problem with the excessive amount of logging has been eliminated by replacing setInterval with setTimeout.

**Comment by mkz212** [comment]
Sorry, after 24 minutes because it will try only 4 times with 360 seconds delay.

**Comment by embee8** [comment]
> If Panasonic makes a maintenance outage of more than 30 minutes, your solution will make the plugin stop working until homebridge is restarted (and that maintenance usually lasts from an hour to three).

The code path we are discussing in this thread is limited to the login right after start-up of Homebridge. This logic isn't triggered if Panasonic performs server maintenance during running operation. The latter is handled in another file and is usually tolerated just fine because we have a valid token which will still work once the servers are up again.

Here is one scenario where your suggestion performs better:
1) When Homebridge is started during a server maintenance which lasts longer than X minutes (X being 24 minutes in the current implementation). Somewhat of an edge case, but still possible. I will check if the network response gives us an indication of whether the login fails because of a wrong password or due to the network being unavailable.
In the first case, retrying makes no sense until the password is updated in the config and Homebridge is restarted.
In the second case, we have to bridge whatever time the server will be down for. I have no data points of historical downtimes, but covering a few hours sounds reasonable.

**Comment by embee8** [comment]
> It's better to remove this switch altogether, because the problem with the excessive amount of logging has been eliminated by replacing setInterval with setTimeout.

This is an interesting point. If someone runs the plugin in debug mode, it logs the network responses including the login transactions. Let's say that response is 50 lines long and we try to log in every hour. That's `50 * 24 = 1,200` lines a day. `1,200 * 30 = 36,000` lines a month. `432,000` lines a year.

The challenge here is that Homebridge attracts a mixed audience, for which design decisions will look differently.
1. People who actively maintain and debug their setup: They like simple, lean solutions that allow them to control as much as possible and don't rock the boat, e.g. through excessive logging.
2. People who buy HOOBS, etc. and expect consumer-grade experiences, not knowing that the underlying packages are hobbyist, open-source projects. They demand a hands-off experience at all times.

Balancing the two involves trade-offs. Threads like this one are helpful for finding the right balance.

**Comment by mkz212** [comment]
So in my opinion, the perfect compromise would be to introduce a mix of my solution and your solution. My solution, plus in the settings, the user can choose after how many attempts the blockade should take place (where 0 means an unlimited number - no switch). And default should be 0 - blockade off.

**Comment by embee8** [comment]
That's not a compromise but offering it all at the cost of added complexity and more maintenance, but fair suggestion. Let's see what data points we get from the latest version. I'm open to revisiting this in the future, but marking the issue as backlog item for the time being since there are some items on the roadmap I want to get to first.

**Comment by mkz212** [comment]
If You want simpler:

```
 .catch(() => {
        this.log.error('Login failed. Skipping device discovery.');
        this.noOfFailedLoginAttempts++;

        if ((this.config.maxAttempts = 0) || (this.noOfFailedLoginAttempts <= this.config.maxAttempts)) {
          this.log.error(
            'The Comfort Cloud server might be experiencing issues at the moment. ' +
            `The plugin will try to log in again in ${this.config.loginDelay / 1000} seconds. ` +
            'If the issue persists, make sure you configured the correct email and password ' +
            'and run the latest version of the plugin. ' +
            'If you run into login errors despite using the correct login details,' +
            'make sure you accepted the latest terms and conditions after logging into the Comfort Cloud app.' +
            'Restart Homebridge when you change your config.',
          );

          this._loginRetryTimeout = setTimeout(this.loginAndDiscoverDevices.bind(this), this.config.loginDelay,);
        }

          else {
          this.log.error(
            'Maximum number of failed login attempts reached ' +
            `(${this.noOfFailedLoginAttempts}). ` +
            'Check your login details and restart Homebridge to reset the plugin.',
          );
        }
      });
```

and add maxAttempts and loginDelay to config so everyone can decide.

**Comment by mkz212** [comment]
Maybe in comfort-cloud.ts in async login() function also change setInterval to setTimeout? And remove this line:

`clearInterval(<NodeJS.Timer>this._loginRefreshInterval);`

And here also add maxAttempts and loginDelay?

**Comment by mkz212** [comment]
Only in the last 2 days Panasonic carried out maintenance and the plugin stopped working after 4 failed connection attempts. I propose to remove this limit immediately and e.g. increase the delay to 10 minutes.

**Comment by mkz212** [comment]
This is my final version. There is no login limit, so you don't need to reset homebridge. It just keeps trying to log in every 5 minutes. In the logs it shows which attempt it is.

in dist/platform.js replace whole function.

```
async loginAndDiscoverDevices() {
        if (!this.platformConfig.email) {
            this.log.error('Email is not configured - aborting plugin start. ' +
                'Please set the field `email` in your config and restart Homebridge.');
            return;
        }
        if (!this.platformConfig.password) {
            this.log.error('Password is not configured - aborting plugin start. ' +
                'Please set the field `password` in your config and restart Homebridge.');
            return;
        }
        this.log.info('Attempting to log into Comfort Cloud.');
        this.comfortCloud.login()
            .then(() => {
            this.log.info('Successfully logged in.');
            this.noOfFailedLoginAttempts = 0;
            this.configureOutdoorUnit();
            this.discoverDevices();
        })
            .catch(() => {
            this.log.error('Login failed. Skipping device discovery.');
            this.noOfFailedLoginAttempts++;
            
		this.log.error(		
			`Failed login attempts: ${this.noOfFailedLoginAttempts}. ` +
			'The plugin will try to login again in 5 minutes.' +
			 'The Comfort Cloud server might be experiencing issues at the moment. ' +
		         'If the issue persists, make sure you configured the correct email and password ' +
			 'and run the latest version of the plugin. ' +
	                 'If you run into login errors despite using the correct login details, ' +
		         'make sure you accepted the latest terms and conditions after logging into the Comfort Cloud app. '
			          );
					  
            this._loginRetryTimeout = setTimeout(this.loginAndDiscoverDevices.bind(this), 300000);
            
           
        });
    }
```

**Comment by embee8** [comment]
Implemented the dynamic login retry interval in [61adb6f](https://github.com/embee8/homebridge-panasonic-ac-platform/commit/61adb6f17562aa0cba350524e3adf7bb89429572). It starts with 6 minutes and overall stretches over 5 hours and 30 minutes. Code review is welcome.

**Comment by mkz212** [comment]
I've found out a few times recently that the maximum number of logins is a bad solution because if Panasonic fails with its cloud, you have to restart homebridge. I know that I proposed to increase the login interval myself, but in the end I came to the conclusion in the tests that the best solution is a simple one: 5 minutes interval, with no limit. 

In Your code: 
- as I say: limit is not god solution. 
- 5h 30 min is too long. 
- in line 157 is little bug - sometimes it's minutes, sometimes hours.

So. If You want inscreasing delay I suggest:
1-5
2-10
3-15
4-30
5-60
Every next 60. 

And please - WITHOUT LIMIT.

**Comment by mkz212** [comment]
P.S 2: I think there should be call to getAppVersion() function if login failed.

**Comment by mkz212** [comment]
So perfect code will be:
- without limit of atempts
- with 5-10 min delay of each atemp
- checking if there is new app version each time login error - if there is new version immediately try login, if not set timeout.

**Comment by mkz212** [comment]
```
async getAppVersion() {
        this.log.info('Attempting to fetch latest Comfort Cloud version from the App Store.');
		this.curVersion = this.platformConfig.appVersionOverride;
		this.log.info(`Current App Version is: ${this.curVersion}.`);
        try {
            const response = await axios_1.default.request({
                method: 'get',
                url: 'https://apps.apple.com/app/panasonic-comfort-cloud/id1348640525',
            });
            const $ = cheerio_1.default.load(response.data);
            const paragraphs = $('p.whats-new__latest__version');
            paragraphs.each((idx, p) => {
                // One or more digit(s), followed by ., followed by one or more digit(s),
                // followed by ., followed by one or more digit(s)
                const matches = $(p).text().match(/\d+(.)\d+(.)\d+/);
                if (Array.isArray(matches)) {
					
					this.newVersion = matches[0];
					
					if (this.newVersion > this.curVersion) {
						//this.platformConfig.latestAppVersion = this.newVersion;
						this.platformConfig.latestAppVersion = null;
	                    this.log.info(`New App Version available: ${this.newVersion}. Currently: ${this.curVersion}.`);
					}
					else {
						this.log.info(`No update available, You have latest App Version: ${this.curVersion}`);
					}
					
                }
                else {
                    this.log.error('Could not find latest app version. '
                        + 'Falling back to override or hard-coded value.');
                }
            });
        }
        catch (error) {
            this.log.debug('Could not fetch latest app version:');
            this.log.debug(JSON.stringify(error, null, 2));
        }
    }
	async loginAndDiscoverDevices() {
		
        if (!this.platformConfig.email) {
            this.log.error('Email is not configured - aborting plugin start. ' +
                'Please set the field `email` in your config and restart Homebridge.');
            return;
        }
        if (!this.platformConfig.password) {
            this.log.error('Password is not configured - aborting plugin start. ' +
                'Please set the field `password` in your config and restart Homebridge.');
            return;
        }
        this.log.info('Attempting to log into Comfort Cloud.');
        this.comfortCloud.login()
            .then(() => {
            this.log.info('Successfully logged in.');
            this.noOfFailedLoginAttempts = 0;
            this.configureOutdoorUnit();
            this.discoverDevices();
        })
        
		.catch(() => {
            this.log.error('Login failed. Skipping device discovery.');
            this.noOfFailedLoginAttempts++;
        
			this.log.error(		
				`Failed login attempts: ${this.noOfFailedLoginAttempts}. ` +
				'The plugin will try to login again in 5 minutes.' +
				'The Comfort Cloud server might be experiencing issues at the moment. ' +
			    'If the issue persists, make sure you configured the correct email and password ' +
				'and run the latest version of the plugin. ' +
		        'If you run into login errors despite using the correct login details, ' +
			    'make sure you accepted the latest terms and conditions after logging into the Comfort Cloud app. '
				);	
				
			if ((this.noOfFailedLoginAttempts == 1) || (this.noOfFailedLoginAttempts %4 == 0)) {	
				this.getAppVersion();	
			}		
		
   		 	this._loginRetryTimeout = setTimeout(this.loginAndDiscoverDevices.bind(this), 300000);

       	 });
	}
```

**Comment by mkz212** [comment]
Without limit on the number of logins. It's really not needed if each attempt is not every 5 minutes only e.g. 10 and each subsequent attempt will be every 6 hours. Then you don't have to finish on the 10th attempt. It's really unnecessary to have to restart homebridge.

**Comment by mkz212** [comment]
If there really must be this limit, I suggest that you can set the number of attempts in the plugin settings, but with the option that if you choose 0, there will be no limit.

**Comment by mkz212** [comment]
I close because I added a pull request in this matter.
