### ISSUE TITLE
Dry Mode instead of Heat

### ISSUE THREAD

**Issue by WaBriones** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#77]
Wondering if switching out Heat from the config with Dry will enable homekit to set it to dry. I can use Homekit to set the AC to auto, but i have to go back to the panasonic app to set it to dry. 

Might also be related to the eco navi option i saw with another related inquiry here. 

from the left, cool, dry, nanoex, auto
@
![IMG_5204](https://github.com/embee8/homebridge-panasonic-ac-platform/assets/10738367/e0ffa8de-15db-4380-904c-7fcf2bf22602)

**Comment by mkz212** [comment]
If I am to be honest, I completely did not understand what you would you like to achieve? If you want additional control such as nanoe, ecoNavi, etc., I add a pull request in this matter. #89

**Comment by jandersonhill** [comment]
As no further comments have been received on this request, please re-open if still relevant. In the meantime several enhancements have been made to control the AC modes from v1.8.0 onwards:

New functions:

- Choice of what to control Oscilate Switch: Swing, Nanoe, Eco Navi, Inside Cleaning.
- Choice what value (for Swing, Nanoe, Eco Navi, Inside Cleaning) should be set with each state change made with Homekit (e.g. activation).
- When the internal unit does not have a temperature sensor, the temperature of the external unit is display, and when there are no both, it is automatically depending on the mode (heating / cooling).
