### ISSUE TITLE
Plugin maintenance update

### ISSUE THREAD

**Issue by embee8** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#79]
The time has come for me to pass the baton to a new maintainer or group of maintainers. I initiated this project in late 2021, building upon @codyc1515's original work, and maintained it with the support of an engaged community.

In recent months, I haven't had the time to actively participate in discussions or implement new features and bug fixes. Nonetheless, I am proud of having made a meaningful contribution to the Homebridge community in the form of this plugin. Many hours went into building it, and I hope that the future maintainers will be able to build upon a well-documented code base and a sturdy release process.

I want to express my gratitude to everyone who contributed with ideas and suggestions, and to the two collaborators who supported the project with a donation.

I would have proposed to transfer the repository to another individual or to a GitHub organization dedicated to maintaining the project. However, I've noticed that @sdamasoc already [created a fork](https://github.com/sdamasoc/homebridge-panasonic-ac-platform), so I could also archive this repository for the project to live on over there. The downside of this approach is that people need to reinstall the plugin as the package name would be different. But I'll happily consider all alternatives.

**Comment by bwp91** [comment]
Homebridge has a repo for this if you are interested!

https://github.com/homebridge/unmaintained-plugins

**Comment by jandersonhill** [comment]
Thanks for all your hard work @embee8 :-)

I supported a fork to help those using the plugin, but struggling to edit the code themselves, to get going again. That said, it would seem to make sense to transfer the repo to @sdamasoc, if he agrees, for continuity.

**Comment by embee8** [comment]
Neat, thank you! I wasn't aware of this initiative. I'll submit a request if we cannot figure out ownership in here. Unless Homebridge prefers to navigate the process themselves?

**Comment by embee8** [comment]
In the spirit of a long-lasting and well-governed project, I am thinking that it would be best to create a GitHub organization with a few people as owners and maintainers of the plugin. @sdamasoc, @mkz212, are you interested in co-owning this? I can give you a rundown on linting, development setup, and release process and advise on any questions or issues around those topics.

**Comment by mkz212** [comment]
@embee8 Welcome back. I'm sorry to read that you resign but I understand. Thank You for Your hard work!

Unfortunately, I am completely unsne with Github and would rather not be a good author. And anyway, I've already written all my ideas and found mistakes (in open topics). Maybe you could last time spend spme time and at least introduce the most important ones into the plugin and release the last update before you "transfer power"?

**Comment by embee8** [comment]
Thank you! Yes, integrating the latest findings and changes would be a good idea. I'll look into it.

**Comment by mkz212** [comment]
The most important thing to do:

1. Change version to 1.19.0 .

2. Add in dist/comfort-cloud.js in four headers:

```
'X-APP-NAME':'Comfort Cloud',
'X-CFC-API-KEY':'0',
'X-APP-TIMESTAMP':(new Date()).toISOString().replace(/-/g, "").replace("T", " ").slice(0, 17),
```

3. I think the problem is in the dist/comfort-cloud.js file, with this part (occurs 3 times):
return Promise.reject(); <- parenthesis cannot be empty.

Each occurrence should be replaced to:

```
in async getDevices() :
return Promise.reject('Comfort Cloud - getDevices(): Error');
```

```
in getDeviceStatus(deviceGuid) :
return Promise.reject(`Comfort Cloud - getDeviceStatus() for GUID '${deviceGuid}': Error`);
```

```
in setDeviceStatus(deviceGuid, parameters) :
return Promise.reject('Comfort Cloud - setDeviceStatus(): Error');
```

**Comment by mkz212** [comment]
6. Fully automatic solution. If the temperature of the indoor unit is not available, the temperature of the outdoor unit will be used. If both are not available, the default values will be used: 8°C for heating and 30°C for cooling.

In dist/accessories/indoor-unit.js :

```
// Current Temperature
// If the temperature of the indoor unit is not available, the temperature of the outdoor unit will be used. 
// If both are not available, the default values will be used: 8°C for heating and 30°C for cooling.
           

// Temperature of 126 from the API = null/failure
if (deviceStatus.insideTemperature < 126) {
   this.service.updateCharacteristic(this.platform.Characteristic.CurrentTemperature, deviceStatus.insideTemperature);
}

else {
   this.platform.log.info('Indoor temperature: is not available');
				
   if (deviceStatus.outTemperature < 126) {
      this.service.updateCharacteristic(this.platform.Characteristic.CurrentTemperature, deviceStatus.outTemperature);
   }
				
   else {
      this.platform.log.info('Outdoor temperature is not available - setting default temperature');		
      this.service.updateCharacteristic(this.platform.Characteristic.CurrentTemperature, (deviceStatus.operationMode === 3) ? 30 : 8);			  
   }
					
} 
```

**Comment by mkz212** [comment]
Thats all what I have. I have these changes and it works without a problem.

**Comment by sdamasoc** [comment]
@embee8 
I’ve agreed to take the maintenance of the project, of course, the help of all contributors will be welcome. 
To make the transfert easier maybe you can put me as maintainer on the homebridge project

**Comment by jandersonhill** [comment]
I'm happy to help, where possible. My days of coding date from a while ago (back when C was in vogue!), but glad to help.

**Comment by embee8** [comment]
Thank you, all. It's great to hear that there is interest in helping out. Within my abilities, I will also keep an eye on things and be around for any questions.

I spent some time today on getting everything functional again and moved the repository to an organization which we can use as a carrier for the project, with a few of us as collaborators/maintainers.

**Comment by sdamasoc** [comment]
It's a good idea, I will close my forked repository.
You can add me as maintainer on your new repository if you want help

**Comment by embee8** [comment]
@sdamasoc, @jandersonhill, I sent invites to manage the newly established organization your way.

**Comment by jandersonhill** [comment]
Thanks @embee8, I've accepted :-)

It'll likely take a little time to navigate the app (especially as I'm coming from a background in C), but it'll be fun! Also, thanks for all your hard work to date.

**Comment by bwp91** [comment]
I've been holding off on looking at verification for

https://github.com/homebridge/verified/issues/576

as have been lightly following this issue here.

Looks like the plan is to keep this plugin maintained? 😁

**Comment by mkz212** [comment]
The most important thing to do:

1. Change version to 1.19.0 . 
DONE IN 1.6.1. 

2. Add in dist/comfort-cloud.js in four headers:

```
'X-APP-NAME':'Comfort Cloud',
'X-CFC-API-KEY':'0',
'X-APP-TIMESTAMP':(new Date()).toISOString().replace(/-/g, "").replace("T", " ").slice(0, 17),
```
DONE IN 1.6.1. 

3. I think the problem is in the dist/comfort-cloud.js file, with Promise.reject(); <- parenthesis cannot be empty.

#83 

4. Small changes in the function that checks if there is new app version, so that the log shows the current version and the new one and more info what to do if login error. 

#85  

5. I've found out a few times recently that the maximum number of logins is a bad solution because if Panasonic fails with its cloud, you have to restart homebridge.

So perfect code will be:
- without limit of atempts or option to chose in setting. 
- checking sometimes if there is new app store version

#86 

6. Small automatic solution: if the temperature of the indoor unit is not available, the temperature of the outdoor unit will be used. If both are not available, the default values will be used: 8°C for heating and 30°C for cooling.

#87 

7. You can choose the default value when starting the AC for: swing, eco navi and inside cleaning and decide what to control the oscilate switch. 

#89 

8. Show more info in logs. 

#88

**Comment by sdamasoc** [comment]
> * checking sometimes if there is new app store version

I think we can implement something here, if in the response contains the message "New version app has been published" then call the update function

**Comment by mkz212** [comment]
Just calling the function makes the latest version saved. In another function it is checked. So there is no need to do anything more. Just call the version check function from the app store on a login error.

It works like this:

If in the settings the app version override field contains a version, this version is used. If the field is empty, the version automatically downloaded from the app store is then used. If it is not possible to download from the app store, the hardcoded version is used last, which is updated when updating the plugin.

**Comment by embee8** [comment]
Please continue the discussion related to new features in separate Issues. I recommend opening one per topic to keep the conversation organised. Closing this one since we clarified the plugin ownership and maintenance question.
