### ISSUE TITLE
New Pull request and some cleaning

### ISSUE THREAD

**Issue by mkz212** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#91]
@embee8 @sdamasoc @jandersonhill

I added 6 PR. Is there anything else I need to do? Could someone take a look?

I also think you can close:
#77 - outdated and without answer
#74 - outdated , think that solved, and I added PR to help in future
#73 - added PR to solve this
#69 - solved and I added PR to help in future
#31 - added PR to solve this

**Comment by jandersonhill** [comment]
I clearly need to figure out notifications on here as I missed these requests and it looks like you've been very busy resolving them!

77 - agreed, I'm not sure what was being asked for here
74 - this approach makes sense
73 - thanks
69 - good thinking
31 - thanks

It looks like one of us needs to merge the PRs. I can test the changes on my own system at the beginning of the week, with the exception of eco mode (which I don't seem to have either).

**Comment by mkz212** [comment]
@jandersonhill I will be very grateful for testing and further action.

As for this ecoMode, unfortunately I do not have it either. I wrote this at the user's request and he tested.

I strongly recommend to release the beta before the official release - surely a group of loyal enthusiastic users (including me) will be willing to test the beta.

**Comment by mkz212** [comment]
@jandersonhill When you release the beta, I will test it on my AC.

**Comment by jandersonhill** [comment]
Thanks, @mkz212. It's been a busier start to the week than expected - I'll aim to get this sorted in the next 48 hours.

**Comment by mkz212** [comment]
@jandersonhill 

I improved all the PR (fine touches).

By the way, I have a small suggestion - tests of new PR could start automatically (in the sense immediately after adding a new PR / code editing).

**Comment by mkz212** [comment]
@jandersonhill I also suggest making a separate branch and merge PRs to it and release a beta from this branch.

**Comment by jandersonhill** [comment]
@mkz212 That was my thinking too :-)

**Comment by mkz212** [comment]
@jandersonhill 

I suggest that in this order merge and release beta:

1. #88 and #90
2. #85 and #86
3. #87
4. #89

Can you run these PR tests? And maybe already create a branch for tests, merge the first and release the beta?

**Comment by jandersonhill** [comment]
> @jandersonhill I also suggest making a separate branch and merge PRs to it and release a beta from this branch.

@mkz212 Have you got a preferred version number for the new beta?

**Comment by mkz212** [comment]
@jandersonhill 1.7.0 will be ok.

**Comment by mkz212** [comment]
@jandersonhill So what's your plan? When the first beta?

**Comment by jandersonhill** [comment]
Look at this this evening, once the children are in bed

**Comment by mkz212** [comment]
@jandersonhill branch name is 1.7a ?

**Comment by jandersonhill** [comment]
That's right. I thought we could test #88, #90, #85, #86 in 1.7a, #87 in 1.7b, and #89 in 1.7c (unless you feel differently)?

In the meantime, I've moved your PR requests to the beta branch.

**Comment by mkz212** [comment]
@jandersonhill 

Beta released for the test should be 1.7.0-beta.1 , 1.7.0-beta.2 etc. So it won't be better to name branch 1.7.0 to maintain consistency? Alternatively 1.7.0a, 1.7.0b, etc.?

Thank you for moving. 

Ready for testing.

**Comment by jandersonhill** [comment]
Yes, that makes sense, I've renamed it. I see the pull requests workflows from outside collaborators has already been changed to 'require approval for first-time contributors'.

**Comment by mkz212** [comment]
@jandersonhill ok so can you merge this first 4 PRs and release first beta?

**Comment by mkz212** [comment]
@jandersonhill I updated another #86 - forgot to add the default value for maxAttempts in case config has never been saved yet.

**Comment by jandersonhill** [comment]
Yes, I'll merge these and release beta 1 shortly.

PS Just seen your other message about #86, understood.

**Comment by jandersonhill** [comment]
Can you see the published changes in the beta branch?

**Comment by mkz212** [comment]
@jandersonhill 

No. 

<img width="555" alt="Zrzut ekranu 2023-11-16 o 23 03 02" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/3a831514-8cb5-47d5-b34e-8e29c369dad5">


Did You publish it via NPM?

**Comment by jandersonhill** [comment]
I didn't publish to NPM just yet in case there were issues we picked up on tomorrow. Shiny, shiny and all that!

**Comment by mkz212** [comment]
@jandersonhill I meant you to post to NPM but AS BETA. Otherwise it can not be installed.

**Comment by jandersonhill** [comment]
Are you comfortable enough to publish on NPM over a manual install first?

**Comment by mkz212** [comment]
@jandersonhill 

It's not about me because I have had these files at my place for a long time. More tests are needed because, I for example, do not have AC with Eco mode and my AC has a temperature sensor in the internal unit and some do not have and this also needs to be tested. Therefore, please release the beta through npm.

**Comment by jandersonhill** [comment]
@mkz212 Good to know. I'm not familiar with publishing to npm and will need to look at the workflow in the morning

**Comment by mkz212** [comment]
@jandersonhill In the plugin settings, I have the official version 1.7.0 came out.

![IMG_4453](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/f5488745-7274-4b68-bb63-42e5c536daeb)

**Comment by mkz212** [comment]
When it comes to publishing to npm, I don't know about it. But here is a good example of the difference between latest and beta: https://coderwall.com/p/l_7acq/publish-beta-versions-of-npm-modules

**Comment by mkz212** [comment]
@jandersonhill Skoro już wyszło to zainstalowałem.

- logs work (But I had to restart HB to start working):
<img width="1159" alt="Zrzut ekranu 2023-11-17 o 07 15 25" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/4a6841be-dc50-4aba-8bdb-76e37c7c77b1">

<img width="894" alt="Zrzut ekranu 2023-11-17 o 07 16 17" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/dae07ff3-8ad5-4596-a6ab-791d2f29eae8">

- no errors in the logs

- the AC itself also works without a problem

- config looks ok

**Comment by mkz212** [comment]
After special introduction of incorrect login details everything works as expected (after a small correction - I did PR).

<img width="1446" alt="Zrzut ekranu 2023-11-17 o 07 34 32" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/bdeebd3a-24f4-410e-b896-c9e8b554343f">

**Comment by mkz212** [comment]
@jandersonhill second PR fix

**Comment by mkz212** [comment]
@jandersonhill 

Since you've already released it as public and not beta, I propose:
- leave this edition as is
- merge two PR that I have now added and release 1.7.1 also as public

in both versions changelog will be:
- a new way to manage errors in logging, in the settings you can select the maximum number of incorrect login attempts (or no limit)
- minor corrections and improvements

Next:
- Create a new branch called `1.8.0-beta`
- Merge another PR - #87
- Release version 1.8.0 beta 1 (as beta!)

**Comment by mkz212** [comment]
@jandersonhill I close this Issue because it does not have to be so public, but we can write here further in a closed thread.

**Comment by jandersonhill** [comment]
> When it comes to publishing to npm, I don't know about it. But here is a good example of the difference between latest and beta: https://coderwall.com/p/l_7acq/publish-beta-versions-of-npm-modules

I'm also new to publishing to NPM - there's a workflow to publish to NPM, but not one to publish a beta which may be what's needed. I'll look at the article above. Later today, I'll publish a new public release with the additional PR's and then look at creating a beta release for 1.8.0.

**Comment by jandersonhill** [comment]
> @jandersonhill Since it came out, I installed it.
> 
> * logs work (But I had to restart HB to start working - i have it running as child bridge so mayby that is the case):
> 
Of course, there are so many lines here because I tested.
> * no errors in the logs
> * the AC itself also works without a problem
> * config looks ok

Appears to work fine in my environment too. No reboot was required in my case, but I'm not using a child bridge.

**Comment by mkz212** [comment]
@jandersonhill Remember to improve the version to 1.7.1 because I did not change it in package.json

**Comment by mkz212** [comment]
@jandersonhill I think you can duplicate this workflow and only change `npm publish` to `npm publish --tag beta` ?

**Comment by jandersonhill** [comment]
Would you like me to update package.json?

**Comment by mkz212** [comment]
@jandersonhill 

> Would you like me to update package.json?

I don't know how you manage the version. is there a suitable command for this workflow? Yes, do it so that it is the right version. Thanks!

**Comment by jandersonhill** [comment]
> @jandersonhill I think you can duplicate this workflow and only change `npm publish` to `npm publish --tag beta` ?

Yes, I saw that was the only difference between what I did last night and the link you sent over earlier today – I tagged it with the version number '1.7.0beta1', rather than simply 'beta'.

**Comment by jandersonhill** [comment]
> @jandersonhill
> 
> > Would you like me to update package.json?
> 
> I don't know how you manage the version. is there a suitable command for this workflow? Yes, do it so that it is the right version. Thanks!

If package.json is updated, I believe package-lock.json should automatically be updated by the npm workflow

**Comment by mkz212** [comment]
@jandersonhill  I know that there are several methods, e.g. change in package.json or the appropriate command in the npm terminal but I have never published myself so I will not help in this matter

**Comment by mkz212** [comment]
@jandersonhill 1.7.1 seems to be ok - no problems that was in 1.7.0 👍

We can merge next PR to next beta (1.8.0) and release as beta.

**Comment by jandersonhill** [comment]
> Yes, I saw that was the only difference between what I did last night and the link you sent over earlier today – I tagged it with the version number '1.7.0beta1', rather than simply 'beta'. You live and learn!

Ok, I've tested this. If you set the package as a pre-release and tag it 'beta' within the npm workflow, it will publish the release as a pre-release, but remain invisible in the NPM repository (unless you use the format `npm install -g homebridge-panasonic-ac-platform@beta`).

That said, if I look at the workflow for last night, the release is clearly marked as pre-release, so I'm a bit confused as to why it was flagged as the latest production version on npm.

**Comment by mkz212** [comment]
@jandersonhill What you fill on github only serves as a changelog. It is the npm that manages the versions and releases. Can you paste me a screenshot or code of this workflow?

**Comment by mkz212** [comment]
> npm install -g homebridge-panasonic-ac-platform@beta

Yes. Each branch can be installed using the appropriate command in the terminal. But only when you publish via npm it will be visible in plugin - update or plugin install alternate version.

**Comment by mkz212** [comment]
@jandersonhill When you publish beta with #87 I suggest you search Issues for people who have problems because they don't have internal temp and invite them to beta test and get feedback. My AC have internal temp sensor so i cannot test this.

**Comment by jandersonhill** [comment]
> > npm install -g homebridge-panasonic-ac-platform@beta
> 
> Yes. Each branch can be installed using the appropriate command in the terminal. But only when you publish via npm it will be visible in plugin - update or plugin install alternate version.

That was after publishing to npm (pre-release versions appear to be invisible unless you use the command above to install manually). It does not show up on HomeBridge. If you change it to a production-ready release and re-publish, it will appear as available on HomeBridge.

This has implications for this evening's 1.8.0-beta release and it might be that we have to uncheck the 'Set as the latest release' option instead.

<img width="1405" alt="Screenshot 2023-11-17 at 16 48 15" src="https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/20860651/f5def54d-a4c0-4117-b317-25038997948c">

**Comment by mkz212** [comment]
@jandersonhill can you show me this workflow for publishing to npm?

**Comment by jandersonhill** [comment]
> @jandersonhill can you show me this workflow for publishing to npm? (Of course, without well-groomed sensitive data like tokens, etc.)

@mkz212 Sure, here it is:

```
# See: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish package to npm

on:
  release:
    types: [created]

jobs:
  # The prepublishOnly script lints and builds the project (see package.json)
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
```

**Comment by mkz212** [comment]
@jandersonhill I thin that if you duplicate it and in second workflow you change `- run: npm publish` to `- run: npm publish --tag beta` it should allow you to publish beta ?

**Comment by jandersonhill** [comment]
Thanks, I'd overlooked this late last night.

**Comment by mkz212** [comment]
@jandersonhill I wonder if I should merge both PRs : #87 and #89. Both of these PR must be tested by people who have specific AC. So mayby merge both? 

But first I would test if beta publishing works. Even if you are to let the current version as 1.8.0 beta 1, nothing wrong will happen.

**Comment by jandersonhill** [comment]
@mkz212 I think it depends on the risk of an issue in one of the PR's creating problems. It certainly simplifies things to test both at the same time. As we plan to mark it as a beta, people should be aware of this.

Your call...

**Comment by mkz212** [comment]
@jandersonhill I would merge both. My AC not have these functions and the code did not create errors - just functions that I do not have did not activate. But a few people confirmed to me that it works for them. And as you say - it will be beta.

**Comment by mkz212** [comment]
@jandersonhill I see that @embee8 spoke in a different thread. Mayby he will advise you on how to release a beta?

**Comment by jandersonhill** [comment]
@mkz212 Yes, it looks like he's going to get back to us on this :-)

In the meantime, I may just modify the workflow temporarily. I'm likely to be offline for the next three hours and will look at this when I get back. Once I've successfully tested that part of the process, I'll release the 1.8.0beta.

Let me know if you want to merge both #87 and #89 into this release.

**Comment by mkz212** [comment]
@jandersonhill Yes - merge both.

**Comment by mkz212** [comment]
@jandersonhill Ok, done! You can merge!

**Comment by mkz212** [comment]
@Jandersonhill

I wonder if with such news not make this version 2.0.0? What do you think?

I think that after releasing the beta, you could start a new Issue, stick it to the top. Generally Issue for beta testers.

New functions:
- choice of what to control Oscilate switch: swing, nanoe, eco navi, inside cleaning)
- choice what value should be at each AC start for: swing, nanoe, eco navi, inside cleaning
- when the internal unit does not have a temperature sensor, the temperature of the external unit is display, and when there are no both, it is automatically depending on the mode (heating / cooling).

What do we need?
- What of these functions does your AC have: swing, nanoe, eco navi, inside cleaning
- Does your AC have a temperature sensor in the internal and external unit? How does it work for you?
- Enable Debug in plugin settings and in the Homebridge settings and paste the response from your AC (it will be in logs) and write what is the status of a given function (swing, nanoe, eco navi, inside cleaning) for this response.

**Comment by mkz212** [comment]
@jandersonhill @embee8 Ahhh, Sunday! What a beautiful day (not at all, it's snowing), birds sing (not either)... Perfect day for the first beta version 1.8.0 and start testing.😉

**Comment by mkz212** [comment]
@jandersonhill @embee8 One thing I want to mark regarding this function with setting the value (nanoe, eco navi, swing, inside cleaning) when starting AC. Apple Home even after changing Rotation Speed sends also command On. So, we will either leave it as it is and it will be values set at startup and actually every AC setting change in Apple Home? Or we will add some if device on to this function? What do you think? I think that if someone sets that he wants to have such a value, that always.

**Comment by jandersonhill** [comment]
> @jandersonhill @embee8 Ahhh, Sunday! What a beautiful day (not at all, it's snowing), birds sing (not either)... Perfect day for the first beta version 1.8.0 and start testing.😉

@mkz212 If we make a decision on whether to treat 1.8.0 as a beta or roll it into the master, I can look at this when I get home (or @embee8 can merge accordingly). Unfortunately, I will be out in London for much of the day. No snow here!

**Comment by jandersonhill** [comment]
> @jandersonhill @embee8 One thing I want to mark regarding this function with setting the value (nanoe, eco navi, swing, inside cleaning) when starting AC. Apple Home even after changing Rotation Speed sends also command On. So, we will either leave it as it is and it will be values set at startup and actually every AC setting change in Apple Home? Or we will add some if device on to this function? What do you think? I think that if someone sets that he wants to have such a value, that always.

If I've understood correctly, I'd have an option in the config screen to ask whether to always start in the following mode or to keep the last mode chosen.

**Comment by embee8** [comment]
> > @jandersonhill @embee8 Ahhh, Sunday! What a beautiful day (not at all, it's snowing), birds sing (not either)... Perfect day for the first beta version 1.8.0 and start testing.😉
> 
> @mkz212 If we make a decision on whether to treat 1.8.0 as a beta or roll it into the master, I can look at this when I get home (or @embee8 can merge accordingly). Unfortunately, I will be out in London for much of the day. No snow here!

No rush. You can remain on standby until I merged everything properly and then I'll clarify the new release workflow to clear our any remaining questions or problems.

**Comment by jandersonhill** [comment]
> No rush. You can remain on standby until I merged everything properly and then I'll clarify the new release workflow to clear our any remaining questions or problems.

Cool, thanks :-) Don't forget to enjoy your Sunday!

**Comment by mkz212** [comment]
> > @jandersonhill @embee8 One thing I want to mark regarding this function with setting the value (nanoe, eco navi, swing, inside cleaning) when starting AC. Apple Home even after changing Rotation Speed sends also command On. So, we will either leave it as it is and it will be values set at startup and actually every AC setting change in Apple Home? Or we will add some if device on to this function? What do you think? I think that if someone sets that he wants to have such a value, that always.
> 
> If I've understood correctly, I'd have an option on the config screen to ask whether to always start in a certain mode or to keep the last mode chosen. I'd certainly like to choose the fan speed so most rooms default to Quiet mode.

@jandersonhill 

You probably didn't understand. I will try to be more accurate.
- We have 4 new options : nanoe, eco navi (it's not eco mode responsible for quiet and powerful - the rotation speed slider is responsible for this), inside cleaning and swing mode.
- in the settings we have a choice for each of these options: forcing it to be turned on, forcing it to be turned off, do nothing (so what was set will be)
- the code is written in such a way that each time you send the ON command is additionally sent a given options. The only problem is that always when you change something for this device in Apple Home, e.g. you change the rotation speed, Apple Home does not send only a command regarding the speed, but also turn on command. So my function then also starts.

And now we have two options: 
- leave this as it is now - and these options will be sent when AC is on and with every change in device (and I think I prefer this option)
- Adding a function to check if AC is turned off and only when you turn on trigger these options.

**Comment by jandersonhill** [comment]
Its current behaviour seems to make sense to me, we could always ask the question, though.

As an aside, I've been meaning to check the code to see if it will accept verbal commands for changing the fan speed, but do you happen to know if they're in there and I simply haven't hit on the right combination of words?!

I'd also been wondering about adding the abbreviation 'aircon' in addition to 'ac' for those of us based in the UK...

**Comment by mkz212** [comment]
@jandersonhill 

What short do you talk about AC and Aircon? About field descriptions?

As for Siri commands, I know that in iOS 17 they changed something. Example: earlier I could say: Hey Siri + device name. And, for example, the lamp turned on. Now I have to combine in the style of Hey Siri + Room name + command + device name.

**Comment by jandersonhill** [comment]
Hi @mkz212 

I mean we can currently say:

- 'Siri, turn air conditioning on' or
- 'Siri, turn ac on'

- but not 'Siri, turn aircon on'.

With iOS 17, we generally haven't had to worry about the room name in the sentence as we have a Homepod in most rooms and it assumes you are talking about the device in that room. For the children's room (as they can't be trusted with a HomePod!), we say something like 'Siri, turn children's nursery lights off' or 'Siri, turn children's nursery air conditioning on'.

I'm just not sure there is a voice command to change the fan speed, or is there?

**Comment by mkz212** [comment]
@jandersonhill  I'm afraid Apple is responsible for the commands. You can give them suggestions. Alternatively, you can create a scene with AC settings and ask Siri to start the scene.

How is beta 1.8.0 and this new pinned Issue for beta testers? 🤔😉

**Comment by jandersonhill** [comment]
@mkz212 Ok, I'll look into the Siri side of things; I'm sure I can fix the 'aircon' bit, though :-) It looks like @embee8 is still fixing things and (in any event) I think I should hold off doing anything until I've had some sleep. 

@embee8 I see you've been doing a lot of work on this! We currently have two additional branches, both with commits ahead and behind the master, but wasn't sure which was which.

**Comment by jandersonhill** [comment]
> @mkz212 Ok, I'll look into the Siri side of things

I realise this is veering slightly off-topic, but to close my question off - I looked it up and found you can use 'Siri, set fan speed to quiet' (previously, I had tried, 'Hey Siri, set ac fan speed to quiet').

**Comment by mkz212** [comment]
@embee8 @jandersonhill 

In one of the open Issue, the user confirmed to me that everything works as it should (eco navi, etc. ). You can close open Issues (Either they are outdated or problems have already been solved). I also think that you can release stable version.

**Comment by jandersonhill** [comment]
Thanks, @embee8. I'd been meaning to check on this, but have been tied up (with family matters). I'm planning to look at this again at some point tomorrow and will look at releasing the beta as a stable version.

**Comment by jandersonhill** [comment]
@mkz212 @embee8 I haven't overlooked this, but I'm still dealing with some family issues and will be until at least Thursday this week. It would be helpful to have a private thread for such occasions :-)

**Comment by mkz212** [comment]
@embee8 @jandersonhill 

- Do you have Discord? Maybe we will continue writing there?
- I think you can release a stable version, a user who has AC with these functions confirmed that it works as it should. I don't see any mistakes either.
- You can close all open errors.
- See on this plugin: https://github.com/kongkx/homebridge-gree-air-conditioner . It offers that for each air conditioning you can choose which switches should be additionally displayed. In the case of Panasonic plugin you could give such to nanoe, eco navi, etc. In addition, you could give two switches: the minimum working time (i.e. how much the climate should be started) and the minimum rest time (i.e. how many minutes from the last turn off can not be turned on).
![IMG_4682](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/34d87283-891e-44be-a4f0-a4499680a3c9)
![IMG_4680](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/b6c3fad5-8012-414c-8814-82bf0afe2328)
![IMG_4677](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/82271669/385592af-d23d-4400-9862-641c4cf93ea0)

**Comment by jandersonhill** [comment]
As it's been tested, I think you're right.

I'm not using Discord at this point in time, I mostly use Teams and WhatsApp for chats. Do you use either of these?

I'll see if I can release the latest version tonight. Do the package.json etc files have the correct version numbers?

**Comment by mkz212** [comment]
@jandersonhill 

I don't have, they persuaded me to discord because there are various discussions about Homebridge, UI and plugins.

I don't remember if there is a version, please correct it if needed.

**Comment by mkz212** [comment]
@jandersonhill please merge my PR. There is version 1.8.1. After that you can release stable version 1.8.1

**Comment by jandersonhill** [comment]
@mkz212 I've created a server 'Homebridge Panasonic AC Platform' on discord for private contributor conversations!

**Comment by jandersonhill** [comment]
@mkz212 I've created a discord server 'Homebridge Panasonic AC Platform (For code contributors)' for private conversations :-)

**Comment by mkz212** [comment]
> @mkz212 I've created a discord server 'Homebridge Panasonic AC Platform (For code contributors)' for private conversations :-)

Can you give me link?

**Comment by jandersonhill** [comment]
Try the server nickname 'HomebridgePanasonicAC'

**Comment by mkz212** [comment]
@jandersonhill i need link with invitation.

**Comment by jandersonhill** [comment]
Sure, this link will work for the next 12 hours: https://discord.gg/dzMp3gp
